name: know_it
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.2
description: Know It?! Quiz App
dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  google_fonts: ^6.3.1
  html_unescape: ^2.0.0
  http: ^1.5.0
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
dev_dependencies:
  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  sqflite_common_ffi: ^2.3.6  
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
flutter:
  assets:
    - assets/
  uses-material-design: true
